#!highlight yaml

heat_template_version: 2013-05-23

parameters:
    vm_image:
      type: string
      label: vm_image
      description: Image for all VMs
      default: ubuntu_multi_nics

    vm_flavor:
      type: string
      label: vm_flavor
      description: Flavor for all VMs
      default: m1.medium

    availability_zone:
      type: string
      label: availability_zone
      description: The Availability Zone to Launch Instance
      default: 'gbp_zone'

resources:
# Creating allow action
    demo_act:
        type: OS::GroupBasedPolicy::PolicyAction
        properties:
            name: demo_act
            action_type: allow
            shared: False

    demo_act_dup:
        type: OS::GroupBasedPolicy::PolicyAction
        properties:
            name: demo_act_dup
            action_type: allow
            shared: False


# Creating a classifier,policy-rule,policy-ruleset(Contract) for ICMP traffic
    demo_class_icmp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_icmp
            protocol: icmp
            direction: bi
            shared: False

    demo_rule_icmp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_icmp
            policy_classifier_id: { get_resource: demo_class_icmp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_icmp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_icmp
            policy_rules: [{ get_resource: demo_rule_icmp }]
            child_policy_rule_sets: []
            shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for any tcp traffic
    demo_class_tcp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_tcp
            protocol: tcp
            direction: bi
            shared: False

    demo_rule_tcp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_tcp
            policy_classifier_id: { get_resource: demo_class_tcp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_tcp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_tcp
            policy_rules: [{ get_resource: demo_rule_tcp }]
            child_policy_rule_sets: []
            shared: False

# Creating a classifier,policy-rule,policy-ruleset(Contract) for any udp traffic
    demo_class_udp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_udp
            protocol: udp
            direction: bi
            shared: False

    demo_rule_udp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_udp
            policy_classifier_id: { get_resource: demo_class_udp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_udp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_udp
            policy_rules: [{ get_resource: demo_rule_udp }]
            child_policy_rule_sets: []
            shared: False

# Creating Policy-RuleSet with proto ICMP & TCP

    demo_ruleset_icmp_tcp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_icmp_tcp
            policy_rules: [{ get_resource: demo_rule_icmp }, { get_resource: demo_rule_tcp }]
            child_policy_rule_sets: []
            shared: False

# Creating Policy-RuleSet with proto ICMP & UDP

    demo_ruleset_icmp_udp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_icmp_udp
            policy_rules: [{ get_resource: demo_rule_icmp },{ get_resource: demo_rule_udp }]
            child_policy_rule_sets: []
            shared: False

# Creating Policy-RuleSet with proto TCP & UDP

    demo_ruleset_tcp_udp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_tcp_udp
            policy_rules: [{ get_resource: demo_rule_tcp }, { get_resource: demo_rule_udp }]
            child_policy_rule_sets: []
            shared: False

# Creating a policy-ruleset(Contract) for allow all protocol(ICMP,TCP,UDP)

    demo_ruleset_all:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_all
            policy_rules: [{ get_resource: demo_rule_icmp }, { get_resource: demo_rule_tcp }, { get_resource: demo_rule_udp }]
            child_policy_rule_sets: []
            shared: False

# Creating a policy-ruleset with no rule

    demo_ruleset_norule:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_norule
            policy_rules: []
            child_policy_rule_sets: []
            shared: False

# Creating L3Policy,L2Policy and PTG and PTs for header SamePTG_SameL2P_SameL3P
    demo_same_ptg_l2p_l3p_l3_policy:
        type: OS::GroupBasedPolicy::L3Policy
        properties:
            name: demo_same_ptg_l2p_l3p_l3p
            ip_pool: "5.5.5.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_same_ptg_l2p_l3p_l2_policy:
        type: OS::GroupBasedPolicy::L2Policy
        depends_on: demo_same_ptg_l2p_l3p_l3_policy
        properties:
            name: demo_same_ptg_l2p_l3p_bd
            l3_policy_id: { get_resource: demo_same_ptg_l2p_l3p_l3_policy }
            shared: False

    demo_same_ptg_l2p_l3p_ptg:
        type: OS::GroupBasedPolicy::PolicyTargetGroup
        properties:
            name: demo_same_ptg_l2p_l3p_ptg
            l2_policy_id: {get_resource: demo_same_ptg_l2p_l3p_l2_policy}
            shared: False


    vm1_data_pt:
        type: OS::GroupBasedPolicy::PolicyTarget
        depends_on: demo_same_ptg_l2p_l3p_ptg
        properties:
            name: vm1_data_pt
            description: 'VM1 Data PT'
            policy_target_group_id: { get_resource: demo_same_ptg_l2p_l3p_ptg }

    vm2_data_pt:
        type: OS::GroupBasedPolicy::PolicyTarget
        depends_on: demo_same_ptg_l2p_l3p_ptg
        properties:
            name: vm2_data_pt
            description: 'VM2 Data PT'
            policy_target_group_id: { get_resource: demo_same_ptg_l2p_l3p_ptg }

    vm3_data_pt:
        type: OS::GroupBasedPolicy::PolicyTarget
        depends_on: demo_same_ptg_l2p_l3p_ptg
        properties:
            name: vm3_data_pt
            description: 'VM3 Data PT'
            policy_target_group_id: { get_resource: demo_same_ptg_l2p_l3p_ptg }


# <<< PLEASE NOTE: DO NOT CHANGE THE Name of VMs, as they have been referred in testcases >>>
# Instantiating VM for Same_PTG_Same_L2P_Same_L3P
    vm1:
        type: OS::Nova::Server
        depends_on: vm1_data_pt
        properties:
            name: "VM1"
            availability_zone: { get_param: availability_zone }
            image: { get_param: vm_image }
            flavor: {get_param: vm_flavor}
            networks:
                - port: {get_attr: [vm1_data_pt, port_id]}
            user_data_format: RAW

    vm2:
        type: OS::Nova::Server
        depends_on: vm1_data_pt
        properties:
            name: "VM2"
            availability_zone: { get_param: availability_zone }
            image: { get_param: vm_image }
            flavor: {get_param: vm_flavor}
            networks:
                - port: {get_attr: [vm2_data_pt, port_id]}
            user_data_format: RAW

    vm3:
        type: OS::Nova::Server
        depends_on: vm3_data_pt
        properties:
            name: "VM3"
            image: { get_param: vm_image }
            flavor: {get_param: vm_flavor}
            networks:
                - port: {get_attr: [vm3_data_pt, port_id]}
            user_data_format: RAW


outputs:

    demo_ruleset_tcp_id:
        value: { get_resource: demo_ruleset_tcp }

    demo_rule_tcp_id:
        value: { get_resource: demo_rule_tcp }

    demo_ruleset_udp_id:
        value: { get_resource: demo_ruleset_udp }

    demo_rule_udp_id:
        value: { get_resource: demo_rule_udp }

    demo_ruleset_icmp_id:
        value: { get_resource: demo_ruleset_icmp }

    demo_rule_icmp_id:
        value: { get_resource: demo_rule_icmp }

    demo_ruleset_icmp_tcp_id:
        value: { get_resource: demo_ruleset_icmp_tcp }

    demo_ruleset_icmp_udp_id:
        value: { get_resource: demo_ruleset_icmp_udp }

    demo_ruleset_tcp_udp_id:
        value: { get_resource: demo_ruleset_tcp_udp }

    demo_ruleset_all_id:
        value: { get_resource: demo_ruleset_all }

    demo_ruleset_norule_id:
        value: { get_resource: demo_ruleset_norule }

    demo_same_ptg_l2p_l3p_ptg_id:
        value: { get_resource: demo_same_ptg_l2p_l3p_ptg }


