#!highlight yaml

# Mandatory: User must not change the below config params
main_setup_heat_temp: '/root/gbpauto/testcases/testcases_integ/heat_integ_config.yaml'
nova_agg_name: 'gbp_agg'
nova_az_name: 'gbp_zone'
heat_stack_name: 'gbpinteg'
key_name: 'gbpkey' #Ensure that it is same as mentioned in heat template

# User editable config params
num_comp_nodes: 2
controller_ip: '172.28.184.65'
compnode1_ip: '172.28.184.63'
compnode2_ip: '172.28.184.64'
comp_nodes: ['172.28.184.63','172.28.184.64']
apic_ip: '172.28.184.60'
leaf_ip: '172.28.184.61'
leaf_node_id: '101'
az_comp_node: 'f5-compute-1.noiro.lab'
#vm_image: '"trusty-multi-if"'
vm_image: 'ubuntu_multi_nics'
leaf1_to_compnode1_conn: 'eth1/1'
leaf1_to_compnode2_conn: 'eth1/2'
