#!highlight yaml

# Mandatory: User must not change the below config params
main_setup_heat_temp: '/root/gbpauto/testcases/testcases_integ/heat_integ_config.yaml'
nova_agg_name: 'gbp_agg'
nova_az_name: 'gbp_zone'

# User editable config params
num_comp_nodes: 2
controller_ip: '172.28.184.45'
compnode1_ip: '172.28.184.46'
compnode2_ip: '172.28.184.47'
comp_nodes: ['172.28.184.46','172.28.184.47']
apic_ip: '172.28.184.40'
leaf1_ip: '172.28.184.41'
leaf2_ip: '172.28.184.42'
leaf1_node_id: '301'
leaf2_node_id: '302'
az_comp_node: 'f3-compute-1.noiro.lab'
vm_image: 'ubuntu_multi_nics'
leaf1_to_compnode1_conn: 'eth1/33'
leaf1_to_compnode2_conn: 'eth1/34'
leaf2_to_compnode1_conn: 'eth1/33'
leaf2_to_compnode2_conn: 'eth1/34'
leaf1_to_spine_conn: 'eth1/49'
leaf2_to_spine_conn: 'eth1/49'

