#!highlight yaml

heat_template_version: 2013-05-23

resources:

# Creating a classifier for all tcp traffic
    demo_class_tcp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_tcp
            protocol: tcp
            direction: in
            shared: False

# Creating a classifier for all udp traffic
    demo_class_udp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_udp
            protocol: udp
            direction: in
            shared: False

# Creating a classifier for ICMP traffic
    demo_class_icmp:
        type: OS::GroupBasedPolicy::PolicyClassifier
        properties:
            name: demo_class_icmp
            protocol: icmp
            direction: bi
            shared: False

# Creating allow action
    demo_act:
        type: OS::GroupBasedPolicy::PolicyAction
        properties:
            name: demo_act
            action_type: allow
            shared: False

# Creating a policy rule and policy rule-set
    demo_rule_tcp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_tcp
            policy_classifier_id: { get_resource: demo_class_tcp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_tcp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_tcp
            policy_rules: [{ get_resource: demo_rule_tcp }]
            child_policy_rule_sets: []
            shared: False

    demo_rule_udp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_udp
            policy_classifier_id: { get_resource: demo_class_udp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_udp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_udp
            policy_rules: [{ get_resource: demo_rule_udp }]
            child_policy_rule_sets: []
            shared: False

    demo_rule_icmp:
        type: OS::GroupBasedPolicy::PolicyRule
        properties:
            name: demo_rule_icmp
            policy_classifier_id: { get_resource: demo_class_icmp }
            policy_actions: [{ get_resource: demo_act }]
            shared: False

    demo_ruleset_icmp:
        type: OS::GroupBasedPolicy::PolicyRuleSet
        properties:
            name: demo_ruleset_icmp
            policy_rules: [{ get_resource: demo_rule_icmp }]
            child_policy_rule_sets: []
            shared: False

# Creating L2 and L3Policy for rendering DHCP
    demo_l3_policy:
        type: OS::GroupBasedPolicy::L3Policy
        properties:
            name: demo_subnet
            ip_pool: "30.30.30.0/24"
            subnet_prefix_length: 28
            shared: False

    demo_srvr_l2_policy:
        type: OS::GroupBasedPolicy::L2Policy
        depends_on: demo_l3_policy
        properties:
            name: demo_srvr_bd
            l3_policy_id: { get_resource: demo_l3_policy }
            shared: False

    demo_clnt_l2_policy:
        type: OS::GroupBasedPolicy::L2Policy
        depends_on: demo_l3_policy
        properties:
            name: demo_clnt_bd
            l3_policy_id: { get_resource: demo_l3_policy }
            shared: False

# Create EPGs for DHCP rendering by Admin
    server_ptg:
        type: OS::GroupBasedPolicy::PolicyTargetGroup
        properties:
            name: server_ptg_1
            l2_policy_id: {get_resource: demo_srvr_l2_policy}
            provided_policy_rule_sets:
                - policy_rule_set_id: { get_resource: demo_ruleset_tcp }
                  policy_rule_set_scope:
            consumed_policy_rule_sets:
                - policy_rule_set_id: { get_resource: demo_ruleset_icmp }
                  policy_rule_set_scope:
            shared: False
            
    client_ptg:
        type: OS::GroupBasedPolicy::PolicyTargetGroup
        properties:
            name: client_ptg_1
            l2_policy_id: {get_resource: demo_clnt_l2_policy}
            consumed_policy_rule_sets:
                - policy_rule_set_id: { get_resource: demo_ruleset_tcp }
                  policy_rule_set_scope:
                - policy_rule_set_id: { get_resource: demo_ruleset_icmp }
                  policy_rule_set_scope: 
            shared: False    

outputs:

    server_ptg_id:
        value: { get_resource: server_ptg }

    client_ptg_id:
        value: { get_resource: client_ptg } 

    demo_l3_policy_id:
        value: { get_resource: demo_l3_policy }
  
    demo_srvr_l2_policy_id:
        value: { get_resource: demo_srvr_l2_policy }

    demo_clnt_l2_policy_id:
        value: { get_resource: demo_clnt_l2_policy }

    demo_ruleset_tcp_id:
        value: { get_resource: demo_ruleset_tcp }

    demo_rule_tcp_id:
        value: { get_resource: demo_rule_tcp }

    demo_ruleset_udp_id:
        value: { get_resource: demo_ruleset_udp }

    demo_rule_udp_id:
        value: { get_resource: demo_rule_udp }

    demo_ruleset_icmp_id:
        value: { get_resource: demo_ruleset_icmp }

    demo_rule_icmp_id:
        value: { get_resource: demo_rule_icmp }
