#!highlight yaml

heat_template_version: 2013-05-23

parameters:

  web_vm_image:
    type: string
    label: web_vm_image
    description: Name of the image for the Web VMs
    default: 'cirros'

  web_vm_flavor:
    type: string
    label: web_vm_flavor
    description: Name of the flavor for the web VMs
    default: 'm1.tiny'

  app_vm_image:
    type: string
    label: app_vm_image
    description: Name of the image for the App VMs
    default: 'cirros'

  app_vm_flavor:
    type: string
    label: app_vm_flavor
    description: Name of the flavor for the App VMs
    default: 'm1.tiny'

  app_rule_set_id:
    type: string
    label: app_rule_set_id
    description: ID of the App PRS

  app_l3_policy_id:
    type: string
    label: app_l3_policy_id
    description: ID of the App L3 Policy

resources:


#### App Tier ####

    app_l2_policy:
        type: OS::Neutron::L2Policy
        properties:
            name: "Application-Network"
            l3_policy_id: { get_param: app_l3_policy_id }
            shared: False

    app_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: "Application-Tier"
            l2_policy_id: { get_resource: app_l2_policy }
            provided_policy_rule_sets: 
                - policy_rule_set_id: { get_param: app_rule_set_id }
                  policy_rule_set_scope: 
            shared: False

    app_server_pt1:
        type: OS::Neutron::PolicyTarget
        depends_on: app_ptg
        properties:
            name: app_server_pt1
            policy_target_group_id: { get_resource: app_ptg }

    app_server1:
        type: OS::Nova::Server
        depends_on: app_server_pt1
        properties:
            name: "Application-Server"
            image: { get_param: app_vm_image }
            flavor: {get_param: app_vm_flavor}
            networks:
                - port: {get_attr: [app_server_pt1, port_id]}
 
#### Web Tier ####

    web_tier_l2_policy:
        type: OS::Neutron::L2Policy
        properties:
            name: "Web-Network"
            l3_policy_id: { get_param: app_l3_policy_id }
            shared: False

    web_ptg:
        type: OS::Neutron::PolicyTargetGroup
        properties:
            name: "Web-Tier"
            l2_policy_id: { get_resource: web_tier_l2_policy }
            consumed_policy_rule_sets: 
                - policy_rule_set_id: { get_param: app_rule_set_id }
                  policy_rule_set_scope: 
            shared: False

    web_server1_pt:
        type: OS::Neutron::PolicyTarget
        depends_on: web_ptg
        properties:
            name: web_server1_pt
            description: 'Pool Member'
            policy_target_group_id: { get_resource: web_ptg }

    web_server2_pt:
        type: OS::Neutron::PolicyTarget
        depends_on: web_ptg
        properties:
            name: web_server2_pt
            description: 'Pool Member'
            policy_target_group_id: { get_resource: web_ptg }

    web_server1:
        type: OS::Nova::Server
        depends_on: web_server1_pt
        properties:
            name: "Web-Server-1"
            image: {get_param: web_vm_image}
            flavor: {get_param: web_vm_flavor}
            networks:
                - port: {get_attr: [web_server1_pt, port_id]}

    web_server2:
        type: OS::Nova::Server
        depends_on: web_server2_pt
        properties:
            name: "Web-Server-2"
            image: {get_param: web_vm_image}
            flavor: {get_param: web_vm_flavor}
            networks:
                - port: {get_attr: [web_server2_pt, port_id]}

outputs:

    app_ptg_id:
        value: { get_resource: app_ptg }

    app_l2_policy_id:
        value: { get_resource: app_l2_policy }

    web_ptg_id:
        value: { get_resource: web_ptg }
