#!highlight yaml

heat_template_version: 2014-10-16

parameters:

  provider_pt_name:
    type: string
    label: Provider PT name
    description: Provider PT name

  consumer_pt_name:
    type: string
    label: Consumer PT name
    description: Consumer PT name

  provider_ptg:
    type: string
    label: Provider PTG id
    description: Provider PTG id

  consumer_ptg:
    type: string
    label: Consumer PTG id
    description: Consumer PTG id

  svc_mgmt_ptg:
    type: string
    label: svc_manangement_ptg
    description: Service Managemnt PTG id

  ids_vm_image:
    type: string
    label: ids_vm_image
    description: Name of the image for the IDS VMs
    default: 'cirros'

  ids_vm_flavor:
    type: string
    label: ids_vm_flavor
    description: Name of the flavor for the IDS VMs
    default: 'm1.medium'

resources:

# Create PTs in uset and app PTGs

    provider_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: { get_param: provider_pt_name }
            policy_target_group_id: { get_param: provider_ptg }

    consumer_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: { get_param: consumer_pt_name }
            policy_target_group_id: { get_param: provider_ptg }

    svc_mgmt_pt:
        type: OS::Neutron::PolicyTarget
        properties:
            name: Svc_Mgmt_IDS_PT
            policy_target_group_id: { get_param: svc_mgmt_ptg }

# Launch IDS appliance

    ids_appliance:
        type: OS::Nova::Server
        properties:
            name: ids_appliance
            image: { get_param: ids_vm_image }
            flavor: { get_param: ids_vm_flavor }
            networks:
                - port: {get_attr: [svc_mgmt_pt, port_id]}
                - port: {get_attr: [consumer_pt, port_id]}
                - port: {get_attr: [provider_pt, port_id]}
