#!highlight yaml

heat_template_version: 2013-05-23

parameters:

  infra_external_segment_name:
    type: string
    label: infra_external_segment_name
    description: Name of the external segment used by infra services
    default: 'Infrastructure'

  infra_external_policy_name:
    type: string
    label: infra_external_policy_name
    description: Name of the external segment used by infra services
    default: 'Infrastructure'

  app_external_segment_name:
    type: string
    label: infra_external_segment_name
    description: Name of the external policy used by infra services
    default: 'App'

  app_external_policy_name:
    type: string
    label: app_external_policy_name
    description: Name of the external policy used by app services
    default: 'App'

  infra_ip_pool:
    type: string
    label: infra_ip_pool
    description: IP Pool used for the Mgmt and Monitoring network
    default: '172.1.0.0/24'

  app_ip_pool:
    type: string
    label: infra_ip_pool
    description: IP Pool used for the Mgmt and Monitoring network
    default: '172.2.0.0/24'

  infra_l3_policy_name:
    type: string
    label: infra_l3_policy_name
    description: Name of the L3 policy for infra
    default: 'Infrastructure'

  app_l3_policy_name:
    type: string
    label: app_l3_policy_name
    description: Name of the L3 policy for app
    default: 'Datacenter'

  port_address_translation:
    type: string
    default: False

resources:

#### Setup External Connectiviy resources ####

    infra_external_segment:
        type: OS::Neutron::ExternalSegment
        properties:
            name: { get_param: infra_external_segment_name }
            port_address_translation: { get_param: port_address_translation }
            subnet_id: { get_resource: external_subnet }
            external_routes:
                - destination: '0.0.0.0/0'
                  nexthop:
            shared: True

    infra_external_policy:
        type: OS::Neutron::ExternalPolicy
        properties:
            name: { get_param: infra_external_policy_name }
            external_segments: [ { get_resource: infra_external_segment } ]
            shared: True

    app_external_segment:
        type: OS::Neutron::ExternalSegment
        properties:
            name: { get_param: app_external_segment_name }
            port_address_translation: { get_param: port_address_translation }
            external_routes:
                - destination: '0.0.0.0/0'
                  nexthop:
            shared: True

    app_external_policy:
        type: OS::Neutron::ExternalPolicy
        properties:
            name: { get_param: app_external_policy_name }
            external_segments: [ { get_resource: app_external_segment } ]
            shared: True

#### Setup L3/L2 Resrouces ####

    infra_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: { get_param: infra_l3_policy_name }
            ip_pool: { get_param: infra_ip_pool }
            shared: True

    infra_l2_policy:
        type: OS::Neutron::L2Policy
        depends_on: infra_l3_policy
        properties:
            name: "Control-Domain"
            l3_policy_id: { get_resource: infra_l3_policy }
            shared: True

    app_l3_policy:
        type: OS::Neutron::L3Policy
        properties:
            name: { get_param: app_l3_policy_name }
            ip_pool: { get_param: app_ip_pool }
            shared: True

    app_l2_policy:
        type: OS::Neutron::L2Policy
        properties:
            name: "Application-Domain"
            l3_policy_id: { get_resource: app_l3_policy }
            shared: False

outputs:

    mgmt_ptg_id:
        value: { get_resource: mgmt_ptg }

    externally_connected_ptg_id:
        value: { get_resource: externally_connected_ptg }

    infra_external_segment_id:
        value: { get_resource: infra_external_segment }

    infra_external_policy_id:
        value: { get_resource: infra_external_policy }

    infra_l3_policy_id:
        value: { get_resource: infra_l3_policy }

    infra_l2_policy_id:
        value: { get_resource: infra_l3_policy }

    app_external_segment_id:
        value: { get_resource: app_external_segment }

    app_external_policy_id:
        value: { get_resource: app_external_policy }

    app_l3_policy_id:
        value: { get_resource: app_l3_policy }

    app_l2_policy_id:
        value: { get_resource: app_l3_policy }
