#!highlight yaml

# Mandatory: User must not change the below config params
dnat_heat_temp: '/root/gbpauto/testcases/heat_temps/heat_tmpl_nat_dp.yaml'
snat_heat_temp: '/root/gbpauto/testcases/heat_temps/heat_snat_only.yaml'
nova_agg_name: 'gbp_agg'
nova_az_name: 'gbp_zone'
heat_stack_name: 'nat'
key_name: 'gbpkey' #Ensure that it is same as mentioned in heat template

# User editable config params
num_comp_nodes: 2
apic_ip: '172.28.184.30'
controller_ip: '172.28.184.35'
ntk_node: '172.28.184.36'
az_comp_node: 'f2-compute-1.noiro.lab'
ext_gw_rtr: '172.28.184.38'
fip1_of_extgw: '1.102.1.1'
fip2_of_extgw: '1.102.2.1'
#vm_image: '"trusty-multi-if"'
vm_image: 'ubuntu_multi_nics'

