#!highlight yaml

# Mandatory: User must not change the below config params
main_setup_heat_temp: '/root/gbpauto/testcases/heat_temps/heat_tmpl_nat_dp.yaml'
nova_agg_name: 'gbp_agg'
nova_az_name: 'gbp_zone'
heat_stack_name: 'gbpstack'
key_name: 'gbpkey' #Ensure that it is same as mentioned in heat template

# User editable config params
num_comp_nodes: 2
apic_ip: '172.28.184.40'
controller_ip: '172.28.184.45'
ntk_node: '172.28.184.46'
az_comp_node: 'f3-compute-1.noiro.lab'
#vm_image: '"trusty-multi-if"'
vm_image: 'ubuntu_multi_nics'

